@host = http://localhost
@port = 5257
@Restaurants.API_HostAddress = https://localhost:7023

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1

###


POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Fine Dining",
  "HasDelivery": true,
  "ContactEmail": "info@test.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "10-101"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1007
Content-Type: application/json

{
  "Name": "Sample Patch",
  "Description": "This is a sample restaurant description",
  "HasDelivery": true
}

###
